### ISSUE TITLE
Credit card example?

### ISSUE THREAD

**Issue by kkimdev** [eCollect/node-fe1-fpe#2]
Hi, it looks like currently modulo is supported up to 10 000 000.  But for 15-digit credit card, don't we need 10^15 modulo?

**Comment by kkimdev** [comment]
@juchiast fyi

**Comment by nanov** [comment]
Hi, and thank you for your comment.

This is true with the current version, due to limitations in node Buffer methods and relay on custom BigNumber implementation.

I've been fooling around with an updated implementation for moden node ( >=**10.8** ) which will take advantage of nodes native BigInt type ( ie remove the current BigNumber custom implementation ) and than could overcome this limitation (v1 branch).

** UPDATE **

I've just released a beta version of v1, one of the major changes under the hood is the usage of V8 ( node ) native BigInt type, which boost up performance and addresses some of the limitations present in the current implementation.

According to my tests  encryption should work as expected with modulo up to 10^16. Please let me know if you encounter any issues with the beta version.

**Comment by kkimdev** [comment]
Great thanks!
